name: Run UnitTests
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'version.py'
      - 'requirements/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'readme.md'
      - 'scripts/**'
  push:
    branches:
      - dev
    paths-ignore:
      - 'version.py'
      - 'requirements/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'readme.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev
          python -m pip install build wheel
      - name: Install core repo and test requirements
        run: |
          pip install .[test]
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install libfann-dev
      - name: Run unittests and generate coverage report
        run: |
          pytest --cov=. --cov-report=xml test/unittests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage.xml,!./cache
          flags: unittests
          name: codecov-umbrella
          verbose: true
